### PR TITLE
Added method to remove absence transaction

### PR DESCRIPTION
**Pull request by jongotlin**

### CODE REVIEW

**Comment by jongotlin** [comment]
Any chance this (and my other prs) can get merged? 🙏

**Comment by agoransson** [comment]
Of course.

I should just give you rights to merge and release also =)

**Comment by jongotlin** [comment]
Thanks for merging. Can you also tag a release?
I don't mind not having merge access but if you want help maintaining this repo I can sure help.

**Comment by agoransson** [comment]
Sorry, I started it this morning but meetings meetings and other activities... then forgot again.

**Comment by agoransson** [comment]
You're it!! =)

**Comment by jongotlin** [comment]
Thanks!

**Pull request merged**
